---
title: Research
---

<style>
  .title{
    display: none;
  }
</style>

<link rel="stylesheet" href="styles.css" type="text/css">

My research interests include urban economics, public finance, fiscal federalism, political economy and applied microeconomics more broadly.

I am currently a reserach assistant on the regional team at the Federal Reserve Bank of Chicago. 

I have worked with [Professor Therese McGuire](https://www.kellogg.northwestern.edu/faculty/directory/mcguire_therese.aspx) on several projects related to fiscal federalism in the United State, Canada, Germany, and Spain. Additionally, I have prepared homeworks and lectures for her [state and local public economics course](https://www4.kellogg.northwestern.edu/syllabus/syllabus_files/KPPI-480-0-31_Fall2018.pdf) for Kellogg MBA students.

My [honors thesis](files/Honors_Thesis.pdf) examined the possibility of correcting sample selection bias with detailed controls, using a large dataset of wholesale used car auctions. My thesis won the Adam Smith Prize for Excellence in Economics.

Additionally, I have worked on a project that investigated how expectations about the future policy environment impacted Deferred Action for Childhood Arrivals (DACA) program participation.

## Published Research

Scott A. Brave, R. Andrew Butters, and **Michael Fogarty**. "[Looking Down the Road with ALEX: Forecasting U.S. GDP](https://www.chicagofed.org/publications/chicago-fed-letter/2020/447)". *Chicago Fed Letter*, No. 447, 2020.

Daniel Aaronson, Scott A. Brave, R. Andrew Butters, and **Michael Fogarty**. "[The Stay-at-Home Labor Market: Google Searches, Unemployment Insurance, and Public Health Orders.](https://www.chicagofed.org/publications/chicago-fed-letter/2020/436)" *Chicago Fed Letter*, No. 436, 2020.

Scott A. Brave, R. Andrew Butters, and **Michael Fogarty**. "[A Closer Look at the Correlation Between Google Trends and Initial Unemployment Insurance Claims.](https://www.chicagofed.org/publications/blogs/chicago-fed-insights/2020/closer-look-google-trends-unemployment)" *Chicago Fed Insights*

Scott A. Brave, R. Andrew Butters, and **Michael Fogarty**. "[Another Look at the Correlation Between Google Trends and Initial Unemployment Insurance Claims.](https://www.chicagofed.org/publications/blogs/chicago-fed-insights/2020/another-look-google-trends-unemployment)" *Chicago Fed Insights*


Scott A. Brave, Ross Cole, and **Michael Fogarty**. "[What Can Revisions to the NFCI Tell Us About Stock Market Volatility?](https://www.chicagofed.org/publications/blogs/chicago-fed-insights/2020/nfci-revisions)" *Chicago Fed Insights*

## Working Papers

Scott A. Brave, **Michael Fogarty**, Daniel Aaronson, Ezra Karger, and Spencer Krane (2021). ``[Tracking U.S. Consumers in Real Time with a New Weekly Index of Retail Trade](https://www.chicagofed.org/publications/working-papers/2021/2021-05).'' *Federal Reserve Bank of Chicago Working Paper*.

Daniel Aaronson, Scott A. Brave, R. Andrew Butters, **Michael Fogarty**, Daniel W. Sacks, and Boyoung Seo (2020). ``Forecasting the Realtime Demand for Unemployment Insurance With Google Trends''. *R&R, International Journal of Forecasting*.

Scott A. Brave, R. Andrew Butters, and **Michael Fogarty** (2020). ``[The perils of working with Big Data and a SMALL framework you can use to avoid them](https://www.chicagofed.org/publications/working-papers/2020/2020-35)'' *Federal Reserve Bank of Chicago Working Paper*.

__Michael Fogarty__, Kenneth Lowande, and August Mense. "[Politics and Policy Take-Up: Evidence from DACA](files/daca.pdf)"

#### Credited as Research Assistant

Daniel Aaronson, Scott A. Brave, R. Andrew Butters, Daniel W. Sacks, and Boyoung Seo. "[Using the eye of the storm to predict the wave of Covid-19 UI claims](https://cepr.org/sites/default/files/news/CovidEconomics9.pdf)". *Covid Economics*, 9, pp. 59-76.

R. Jason Faberman and Daniel Hartley. "[The Relationship between Race, Type of Work, and Covid-19 Infection Rates](https://www.chicagofed.org/publications/working-papers/2020/2020-18)". *Chicago Fed Working Paper*, 2020.

Teresa Garcia-Milà, Therese J. McGuire, and Wallace E. Oates. "[Strength in diversity? Fiscal federalism among the fifty US states](https://link.springer.com/article/10.1007/s10797-018-9485-4)" *International Tax and Public Finance*, 25(4), pp.1071-1091.

Teresa Garcia-Milà and Therese J. McGuire. "[When Theory Meets Practice: Can We Implement the Optimal Fiscal
Federal Structure?](http://www.crei.cat/wp-content/uploads/2019/03/TMP.pdf)" *Work in progress*.